<script>const BOZO_MINT='8ncucXv6U6epZKHPbgaEBcEK399TpHGKCquSt4RnmX4f';const MORALIS_URL=`https://solana-gateway.moralis.io/token/mainnet/holders/${BOZO_MINT}`;const MORALIS_API_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjVmMDE5ZTE0LWM2YjYtNDVhMC04MDNhLTA5MGFlNGQ2NDUxNyIsIm9yZ0lkIjoiNDQ0MjMwIiwidXNlcklkIjoiNDU3MDU4IiwidHlwZUlkIjoiY2E3ZmM0ZjAtNWRlMy00YjJjLTk0ZWEtMWZjZmM3MTI5MmEzIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NDU4MTc0NzgsImV4cCI6NDkwMTU3NzQ3OH0.0Axf0KJ14urmvjoa4AB2bF-GeO19-2c7_xzDovBU1fg';const H_API_KEY='f9657af9-8f69-444a-85f8-db396d07c0e0';const HELIUS_RPC_URL=`https://mainnet.helius-rpc.com/?api-key=${H_API_KEY}`;const SUPPLY=1_000_000_000;const DISPLAY_COUNT=21;const fmt=n=>Number(n).toLocaleString();const short=a=>a?`${a.slice(0,4)}…${a.slice(-4)}`:'N/A';async function refresh(){document.getElementById('holdersCount').textContent='…';document.getElementById('topClownsPct').textContent='…%';const tbody=document.getElementById('lb');tbody.innerHTML='<tr><td colspan="4">Loading…</td></tr>';try{const resp=await fetch(MORALIS_URL,{headers:{'X-API-Key':MORALIS_API_KEY}});if(!resp.ok)throw new Error(`Moralis responded ${resp.status}`);const j=await resp.json();if(j.totalHolders===undefined){throw new Error('`totalHolders` missing in response')}
document.getElementById('holdersCount').textContent=fmt(j.totalHolders)}catch(e){console.error('Moralis fetch failed:',e);document.getElementById('holdersCount').textContent='—'}
let accs=[];try{const r=await fetch(HELIUS_RPC_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getTokenLargestAccounts',params:[BOZO_MINT]})});const j=await r.json();if(!j.result?.value)throw new Error('Helius RPC malformed');accs=j.result.value.slice(0,DISPLAY_COUNT)}catch(e){tbody.innerHTML=`<tr><td colspan="4" style="color:red;">Error: ${e.message}</td></tr>`;return}
let infos=[];try{const addresses=accs.map(a=>a.address);const r2=await fetch(HELIUS_RPC_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:2,method:'getMultipleAccounts',params:[addresses,{encoding:'jsonParsed'}]})});const j2=await r2.json();infos=j2.result.value}catch(e){tbody.innerHTML=`<tr><td colspan="4" style="color:red;">Error: ${e.message}</td></tr>`;return}
const rows=infos.map((info,i)=>{const t=info.data.parsed.info.tokenAmount;const amt=t.uiAmount??(t.amount/10**t.decimals);const owner=info.data.parsed.info.owner;return{rank:i+1,owner,amt,pct:(amt/SUPPLY*100).toFixed(2)+'%'}});const top5=rows.slice(0,5).reduce((s,r)=>s+r.amt,0);document.getElementById('topClownsPct').textContent=(top5/SUPPLY*100).toFixed(2)+'%';tbody.innerHTML=rows.map(r=>`
      <tr>
        <td class="rank">${r.rank}</td>
        <td class="address ${r.rank===1?'lp':''}" title="${r.owner}">${short(r.owner)}</td>
        <td>${fmt(r.amt)}</td>
        <td>${r.pct}</td>
      </tr>
    `).join('')}
window.addEventListener('DOMContentLoaded',()=>{refresh();setInterval(refresh,300_000)});</script>
